import logging
from typing import Any, Dict
from app.chatbot.agent_executor import MainAgentChatbot
import streamlit as st

from dotenv import load_dotenv
from langchain_core.messages import AIMessage, HumanMessage
from langchain.callbacks.base import BaseCallbackHandler
load_dotenv()
from langchain_core.outputs.llm_result import LLMResult

def extract_final_answer(agent_response):
    final_answer_marker = "Final Answer:"
    if final_answer_marker in agent_response:
        final_answer = agent_response.split(final_answer_marker)[-1].strip().replace("```", "")
        return final_answer
    return "Sorry, the context is not clear enough to answer."

### Utils
class StreamlitCallbackHandler(BaseCallbackHandler):
    def __init__(self, placeholder):
        self.placeholder = placeholder
        self.current_text = ""

    # def on_tool_error(self, error):
    #     logging.info(f"on_tool_error {error}")

    # def on_llm_error(self, error):
    #     logging.info(f"on_llm_error {error}")

    def on_chain_error(self, error, *, run_id, parent_run_id = None, **kwargs: Any):
        logging.info("on_chain_error")
        logging.info(error)
        if 'Final Answer' not in self.current_text:
            self.placeholder.markdown('Sorry, the context is not clear enough to answer or invalid format in answer.')
        pass

    def on_agent_finish(self, finish, *, run_id, parent_run_id = None, **kwargs: Any):
        # logging.info(f"on_agent_finish {finish.return_values['output']}")
        if 'Final Answer' not in self.current_text:
            self.placeholder.markdown('Sorry, the context is not clear enough to answer.')
        
    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        """Called every time a new token is generated by the language model."""
        self.current_text += token
        if 'Final Answer' in self.current_text:
            logging.info(f"on_llm_new_token")
            final_answer = extract_final_answer(self.current_text)
            self.placeholder.markdown(final_answer)
            # st.session_state.chat_history.append(AIMessage(content=final_answer)) 

main_agent_chatbot = MainAgentChatbot()
def get_response(user_query):
    response_placeholder = st.empty()

    # Create an instance of the callback handler
    stream_handler = StreamlitCallbackHandler(response_placeholder)

    # Step 3: Pass the callback handler to the agent executor invoke method
    return main_agent_chatbot.run_with_memory(user_query, stream_handler)['output']

#### Main app
# Show title and description.
st.title("💬 Ecommerce Chatbot")
st.write(
    "This is a simple Ecommerce Chatbot that uses OpenAI's GPT-3.5 model to generate responses. "
)

# session state
if "chat_history" not in st.session_state:
    st.session_state.chat_history = [
        AIMessage(content="Hello, I am an e-commerce chatbot. How can I help you?"),
    ]

# conversation
for message in st.session_state.chat_history:
    if isinstance(message, AIMessage):
        with st.chat_message("AI"):
            st.write(message.content)
    elif isinstance(message, HumanMessage):
        with st.chat_message("Human"):
            st.write(message.content)

# user input
user_query = st.chat_input("Type your message here...")
if user_query is not None and user_query != "":
    st.session_state.chat_history.append(HumanMessage(content=user_query))

    with st.chat_message("Human"):
        st.markdown(user_query)

    with st.chat_message("AI"):
        with st.spinner("Processing..."):
            chain_response = get_response(user_query)
            st.session_state.chat_history.append(AIMessage(content=chain_response)) 
