from typing import Any
from app.chatbot.agent_executor import run_with_memory
import streamlit as st

from dotenv import load_dotenv
from langchain_core.messages import AIMessage, HumanMessage
from langchain.callbacks.base import BaseCallbackHandler
load_dotenv()

def extract_final_answer(agent_response):
    final_answer_marker = "Final Answer:"
    if final_answer_marker in agent_response:
        final_answer = agent_response.split(final_answer_marker)[-1].strip()
        return final_answer
    return "No final answer found."

### Utils
class StreamlitCallbackHandler(BaseCallbackHandler):
    def __init__(self, placeholder):
        self.placeholder = placeholder
        self.current_text = ""

    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        """Called every time a new token is generated by the language model."""
        self.current_text += token
        
        if 'Final Answer' in self.current_text:
            final_answer = extract_final_answer(self.current_text)
            self.placeholder.markdown(final_answer)
            # st.session_state.chat_history.append(AIMessage(content=final_answer)) 

def get_response(user_query):
    response_placeholder = st.empty()

    # Create an instance of the callback handler
    stream_handler = StreamlitCallbackHandler(response_placeholder)

    # Step 3: Pass the callback handler to the agent executor invoke method
    return run_with_memory(user_query, stream_handler)['output']

#### Main app
# Show title and description.
st.title("💬 Ecommerce Chatbot")
st.write(
    "This is a simple Ecommerce Chatbot that uses OpenAI's GPT-3.5 model to generate responses. "
)

# session state
if "chat_history" not in st.session_state:
    st.session_state.chat_history = [
        AIMessage(content="Hello, I am an e-commerce chatbot. How can I help you?"),
    ]

# conversation
for message in st.session_state.chat_history:
    if isinstance(message, AIMessage):
        with st.chat_message("AI"):
            st.write(message.content)
    elif isinstance(message, HumanMessage):
        with st.chat_message("Human"):
            st.write(message.content)

# user input
user_query = st.chat_input("Type your message here...")
if user_query is not None and user_query != "":
    st.session_state.chat_history.append(HumanMessage(content=user_query))

    with st.chat_message("Human"):
        st.markdown(user_query)

    with st.chat_message("AI"):
        with st.spinner("Processing..."):
            chain_response = get_response(user_query)
            st.session_state.chat_history.append(AIMessage(content=chain_response)) 
